### ISSUE TITLE
Implement a test framework

### ISSUE THREAD

**Issue by jrkong** [jrkong/pySearch#2]
Add unit tests to pySearch. A good place to get started would be Python's default [unittest](https://docs.python.org/3.7/library/unittest.html) module.

**Comment by jrkong** [comment]
Another test framework to consider would be [pytest](https://docs.pytest.org/en/latest/getting-started.html)

**Comment by giantpanpan** [comment]
Hi @jrkong can I take this issue?

**Comment by jrkong** [comment]
Go ahead! To futureproof the project a bit I'd suggest looking at the [pytest](https://docs.pytest.org/en/latest/getting-started.html) framework as it should scale better then the [unittest](https://docs.python.org/3.7/library/unittest.html) module.

**Comment by jrkong** [comment]
As per my conversation with @giantpanpan earlier today I'll take this issue so we have a basic coverage to avoid regressions and @giantpanpan will increase overall test coverage.
