### ISSUE TITLE
Use Flake!

### ISSUE THREAD

**Issue by SeanPrashad** [jrkong/pySearch#29]
http://flake8.pycqa.org/en/latest/

**Comment by alexander-ponomaroff** [comment]
Is anyone currently working on this? If not, I would like to integrate flake8 with pySearch!

**Comment by alexander-ponomaroff** [comment]
I currently checked all current flake8 issues in the files that are currently in the master branch. I am now putting all the current issues to be ignored in a setup.cfg file, once this file is up, we can start getting rid of the issues one-by-one. I am also now working on integrating pep8speaks bot into the pySearch project. Whenever somebody will make a contribution, they will need to check with flake8 locally, and when they create the pull request, the pep8speaks bot will be able to check the same issues.

@jrkong

**Comment by alexander-ponomaroff** [comment]
@jrkong Check out how pep8speaks will work, every time a person commits it will check. #34

**Comment by jrkong** [comment]
Fixed by #31.
